### ISSUE TITLE
Enabling Darcula Hides All Enigma Icons

### ISSUE THREAD

**Issue by TehcJS** [Legacy-Fabric/yarn#106]
When Enigma's theme is switched to Darcula, the icons in all of the menus disappear except for class/interface icons (found when expanding namespace folders).

**Comment by TehcJS** [comment]
no stop why did it mark it as enhancement

**Comment by BluCobalt** [comment]
crob

**Comment by hYdos** [comment]
im 90% sure this is an upstream problem

**Comment by TehcJS** [comment]
just fork it and fix it then

**Comment by BoogieMonster1O1** [comment]
why are you reporting this here?
report it to [FabricMC/Engima](https://github.com/FabricMC/Enigma)
