### ISSUE TITLE
There is no Blaze3d in < 1.15

### ISSUE THREAD

**Issue by MenschenToaster** [Legacy-Fabric/yarn#113]
**Type**  
Package

**Describe where the element is**  
com.mojang.blaze3d.platform

**Description of the element**  
Contains GlStateManager and AdvancedOpenGlManager

**Expected name**  
net.minecraft.client.gl.plaform

**Additional Context**
Blaze3d was introduced in 1.15 not 1.8...

**Comment by BoogieMonster1O1** [comment]
> **Type**
> Package
> 
> **Describe where the element is**
> com.mojang.blaze3d.platform
> 
> **Description of the element**
> Contains GlStateManager and AdvancedOpenGlManager
> 
> **Expected name**
> net.minecraft.client.gl.plaform
> 
> **Additional Context**
> Blaze3d was introduced in 1.15 not 1.8...

This package exists in 1.14 yarn as well

**Comment by BoogieMonster1O1** [comment]
![image](https://user-images.githubusercontent.com/62552372/115178357-bee0db80-a0ee-11eb-9924-456467d1095a.png)
![image](https://user-images.githubusercontent.com/62552372/115178443-e89a0280-a0ee-11eb-9d2a-092533292e68.png)
also in 1.14 snapshots lol

**Comment by BoogieMonster1O1** [comment]
since we mirror upstream in names we can't do anything about this
