### ISSUE TITLE
[1.12.2] Local Builds Publishing to maven.legacyfabric.net

### ISSUE THREAD

**Issue by halotroop2288** [Legacy-Fabric/yarn#119]
Since merging #118, Yarn has published a build called `1.12.2+build.local`, which should only happen when the `publishToMavenLocal` task is run. Never during any other task.

**Comment by BluCobalt** [comment]
Gradle problem or ga problem?

**Comment by halotroop2288** [comment]
> Gradle problem or ga problem?

Gradle.

https://github.com/Legacy-Fabric/yarn/commit/370a56d1d48a9b068c5024c049de591b11921387#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7R37

**Comment by halotroop2288** [comment]
Possibly both, actually. `publishToMavenLocal` should *not* be running during normal publishing.

**Comment by BluCobalt** [comment]
If you pr a fix for it, I would be happy to merge it.

**Comment by BluCobalt** [comment]
It would have to be a gradle problem because I just rewrote the workflows and a +local version came up in the maven again

**Comment by halotroop2288** [comment]
I suppose the publish(ToMaven) tasks could be depending on publishToMavenLocal, but that would be even more concerning...

**Comment by BluCobalt** [comment]
Yeah, that was my thought.

**Comment by BluCobalt** [comment]
Supposed to be fixed by #120
