### ISSUE TITLE
Incorrect method name : shutdown should be called tick

### ISSUE THREAD

**Issue by SRAZKVT** [Legacy-Fabric/yarn#149]
**Type**  
Method

**Describe where the element is**  
net/minecraft/server/MinecraftServer.shutdown

**Description of the element**  
The method ticks the server

**Expected name**  
tick

**Additional Context**
The method ticks the server, and thus shouldn't be called shutdown

**Comment by BluCobalt** [comment]
For what version?

**Comment by SRAZKVT** [comment]
found in 1.8.9, but maybe it is in other versions too
