### ISSUE TITLE
Incorrect mapping name : getServerWorld should be called getWorld

### ISSUE THREAD

**Issue by SRAZKVT** [Legacy-Fabric/yarn#150]
**Type**  
Method

**Describe where the element is**  
net/minecraft/util/HopperProvider.getServerWorld

**Description of the element**  
The element is a method in an interface, which returns a World

**Expected name**  
getServer

**Additional Context**
The interface HopperProvider is implemented in two classes : HopperBlockEntity and HopperMinecartEntity. In HopperMinecartEntity, there is no issue since the method is in the class itself and just returns this.world, however, HopperBlockEntity, i assume at least, uses the method getWorld, which is present in BlockEntity. This results in the method being, by default, inaccessible, and thus, whenever a mixin into HopperBlockEntity is created, if a method under the name getServerWorld isn't created, then the mod will simply crash.

**Comment by SRAZKVT** [comment]
woups , expected name is getWorld, not getServer

**Comment by arthurbambou** [comment]
mappings changed quite a lot since last month, I don't think this is relevant anymore

**Comment by SRAZKVT** [comment]
it is very much still relevant, and very much not fixed anymore

**Comment by arthurbambou** [comment]
Fixed by naming both BlockEntity's and HopperProvider's method "getEntityWorld"

**Comment by SRAZKVT** [comment]
why not just call it "getWorld" ? makes more sense and isn't misleading (could think getEntityWorld have to do with entities, which isn't the case)

**Comment by arthurbambou** [comment]
can't because of some conflicts with other method also named getWorld.
getEntityWorld is only in BlockEntity classes + HopperMinecart class...
