### ISSUE TITLE
genSources doesn't work on build.422+

### ISSUE THREAD

**Issue by YetAnotherMcModder** [Legacy-Fabric/yarn#253]
Running `gradlew genSources` (in the example mod) on yarn **build.422+** (since the _buildscript_ update)
It fails with the following error:

```
Execution failed for task ':unpickJar'.
> Could not resolve all files for configuration ':unpick'.
   > Could not find net.legacyfabric.unpick:unpick-cli:2.3.0.
```
After some investigation I have found that in `/unpick-definitions/unpick.json` the wrong unpickgroup packagename is specified:
`    "unpickGroup": "net.legacyfabric.unpick",`
after correcting it to:
`    "unpickGroup": "net.fabricmc.unpick",`

It successfully resolved it, but then I got a new error:
`Exception in thread "main" daomephsta.unpick.constantmappers.datadriven.parser.UnpickSyntaxException: Line 1: Missing version`

This is caused by missing data from 2 yarn files (from the resulting build):
```
yarn-v2.jar\extras\definitions.unpick
yarn-mergedv2.jar\extras\definitions.unpick
```
In fabric's yarn it works completely fine.
After looking more into it, trying ways to fix it, I still have no idea why no data is written into
the `definitions.unpick` files.

**Comment by Reoseah** [comment]
It seems that before build 422, jars didn't contain`extras` folder at all, but then they got `extras/unpick.json` and no `extras/definitions.unpick`, adding any `.unpick` file to sources creates `extras/definitions.unpick` file in the jar and fixes this issue.

Fabric Yarn always had some unpick definitions so it never happened to them

**Comment by arthurbambou** [comment]
Fixed in build.450+
