### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by Bixilon** [Legacy-Fabric/yarn#261]
So, first of all: Thank you for the project. I am completely focusing on 1.13.2 here (are there mappings for 1.13.1 and 1.13?). I will probably use it for 1.12.2 in the future.

How do I get the yarn mappings? I am checking https://meta.legacyfabric.net/v2/versions/yarn and getting a build id of `+build.451`, so I assume the url needs to be https://repo.legacyfabric.net/repository/legacyfabric/net/fabricmc/yarn/1.13.2+build.451/yarn-1.13.2+build.451-v2.jar, but I only get resources under https://repo.legacyfabric.net/repository/legacyfabric/net%2Ffabricmc%2Fyarn%2F1.13.2%2Bbuild.202206171821%2Fyarn-1.13.2%2Bbuild.202206171821-v2.jar.

The second thing is: Why are there only `-old` intermediary mappings for 1.13.2, see https://repo.legacyfabric.net/#browse/browse:legacyfabric:net%2Ffabricmc%2Fintermediary-old%2F1.13.2. I need the current ones for https://repo.legacyfabric.net/#browse/browse:legacyfabric:net%2Ffabricmc%2Fintermediary%2F1.13.2. The old ones do map, but they are completely wrong.

Thanks for any future help!

Moritz

**Comment by arthurbambou** [comment]
On the maven, look at `net.legacyfabric` instead of `net.fabricmc`

**Comment by arthurbambou** [comment]
You can get more info on our discord server.

**Comment by Bixilon** [comment]
Thanks, solved it for me!
