### ISSUE TITLE
OverworldChunkGenerator; SetBaseBiomesLayer

### ISSUE THREAD

**Issue by valoeghese** [Legacy-Fabric/yarn#67]
**Names of the classes**  
OverworldChunkGenerator is the only unmapped ChunkProvider. (at least in api)
The method with lots of maths is the `populateNoise` method (shapeChunk is better tho imo)
The method which has strongholds and dungeons and stuff is `generateFeatures`

class_601 is `SetBaseBiomesLayer`

Layer.method_1829 is `sample` or `sampleArea` (modern layers do one sample at a time and yarn uses `sample` for those, but the old 1.8.9 ones do multiple "samples" at the same time in an area)

class_604.method_1825 allocates an int array of the specified size

Biome.field_405 is `id` or `rawId`

Layer.method_1827 is `nextInt`

**Additional Context**
yes

**Comment by BoogieMonster1O1** [comment]
Fixed in #65
